<?xml version="1.0"?> <!--this tag must be in the first line of the xml files-->
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="dual_arm_robot">
<!-- rosrun xacro xacro.py dual_arm_robot.urdf.xacro >  dual_arm_robot.urdf -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:arg name="prefix_left" default="left_"/>
  <xacro:arg name="prefix_right" default="right_"/>
  <xacro:arg name="limited" default="true"/>

  <!-- common stuff -->
  <xacro:include filename="$(find ur_description)/urdf/common.gazebo.xacro"/>

  <!-- ur5 -->
  <xacro:include filename="$(find dual_arm_robot_description)/urdf/ur5.urdf.xacro"/> 
  <!-- robotiq 2 finger gripper -->
  <xacro:include filename="$(find robotiq_2f_c2_gripper_visualization)/urdf/robotiq_c2_model_macro.xacro"/>
  <!-- ft300 -->
	<xacro:include filename="$(find robotiq_ft_sensor)/urdf/robotiq_fts300.urdf.xacro" />

	  <!-- the robotiq 3 fingersf gripper macro -->
  <xacro:include filename="$(find robotiq_3f_gripper_visualization)/cfg/robotiq-3f-gripper_articulated_macro.xacro"/>

  <!-- endeffector
  <xacro:include filename="$(find dual_arm_robot_description)/urdf/endeffector.urdf.xacro"/>
-->

  <xacro:property name="robot_horizontal_stand_width" value="0.5"/>
	<xacro:property name="robot_vertical_stand_height" value="1.2"/>
	
	<!-- color macros -->
	<xacro:macro name="material_orange_transparent">
		<material name="orange_transparent">
			<color rgba="1 0.5 0 0.4"/>
		</material>
	</xacro:macro>
	<xacro:macro name="material_blue_transparent">
		<material name="blue_transparent">
			<color rgba="0 0.8 1 0.4"/>
		</material>
	</xacro:macro>
	
	<xacro:material_orange_transparent />
	<xacro:material_blue_transparent />
  	
  <!-- end of color macros -->
  <!-- Stand macros -->
  <link name="stand1">
		<visual>
		<geometry>
		<cylinder radius="0.08" length="0.8"/>
		</geometry>
		<material name="orange_transparent"/>
		</visual>
		<collision>
		<geometry>
		<cylinder radius="0.08" length="0.8"/>
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>
	
	<link name="stand2">
		<visual>
		<geometry>
		<cylinder radius="0.07" length="${robot_horizontal_stand_width}"/>
		</geometry>
		<material name="orange_transparent"/>
		</visual>
		<collision>
		<geometry>
		<cylinder radius="0.07" length="${robot_horizontal_stand_width}"/>
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>	
<link name="stand_Base">
		<visual>
		<geometry>
		<cylinder radius="0.5" length="0.7"/>
		</geometry>
		<material name="orange_transparent"/>
		</visual>
		<collision>
		<geometry>
		<cylinder radius="0.5" length="0.7"/>
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>



	<link name="table">
		<visual>
			<geometry>
				<box size="1 1.2 0.92" />
			</geometry>
			<material name="orange_transparent"/>
		</visual>
		<collision>
			<geometry>
		<box size="1 1.2 0.92" />
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>
  <joint name="table_joint" type="fixed" >
    <parent link="world" />
    <child link="table" />
    <origin xyz="-1 0 0.46" rpy="0 0 0" />
</joint>


	<link name="wall">
		<visual>
			<geometry>
				<box size="1 1 3" />
			</geometry>
			<material name="blue_transparent"/>
		</visual>
		<collision>
			<geometry>
		<box size="1 1 3" />
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>
  <joint name="wall_joint" type="fixed" >
    <parent link="world" />
    <child link="wall" />
    <origin xyz="-1.6 -1.55 1.5" rpy="0 0 0" />
</joint>

<link name="wall1">
		<visual>
			<geometry>
				<box size="0.01 2 3" />
			</geometry>
			<material name="blue_transparent"/>
		</visual>
		<collision>
			<geometry>
		<box size="0.01 2 3" />
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>
  <joint name="wall_joint1" type="fixed" >
    <parent link="world" />
    <child link="wall1" />
    <origin xyz="0.5 0 1.5" rpy="0 0 0" />
</joint>

<link name="wall2">
		<visual>
			<geometry>
				<box size="2 0.01 3" />
			</geometry>
			<material name="blue_transparent"/>
		</visual>
		<collision>
			<geometry>
		<box size="2 0.01 3" />
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>
  <joint name="wall_joint2" type="fixed" >
    <parent link="world" />
    <child link="wall2" />
    <origin xyz="-1 1.4 1.5" rpy="0 0 0" />
</joint>

  <!-- End of stand macros-->
  <!-- Place the stand in the world -->
  <link name="world"/>
    <!-- place world reference -->
  <joint name="world_to_stand_Base" type="fixed">
		<parent link="world"/>
		<child link="stand_Base"/>
		<origin xyz="0 0 0.35" rpy="0 0 0"/>
	</joint>

	<joint name="Base_to_stand1" type="fixed">
		<parent link="stand_Base"/>
		<child link="stand1"/>
		<origin xyz="0 0 0.6" rpy="0 0 0"/>
	</joint>


	<joint name="stand1_to_stand2" type="fixed">
		<parent link="stand1"/>
		<child link="stand2"/>
		<origin xyz="0 0 0.25" rpy="1.57 1.57 0"/>
	</joint>
	
<!-- place a table 
  	<joint name="world_to_table" type="fixed">
		<parent link="world"/>
		<child link="table"/>
		<origin xyz="-1 0 0.5" rpy="0 0 0"/>
	</joint>
	-->
  <!-- place ur5 left arm    -->
  <xacro:ur5_robot prefix="$(arg prefix_left)" joint_limited="$(arg limited)"/>
  <joint name="stand2_to_left_arm" type="fixed">
    <parent link="stand2"/>
    <child link ="$(arg prefix_left)base_link"/>
   <origin xyz="0 0 ${(robot_horizontal_stand_width/2)}" rpy="${PI/4.0} 0 0"/>
  </joint>

  <!-- place robotiq_fts300 to left arm -->
	
  <xacro:robotiq_fts300 prefix=""/>
  <!-- mount the fts to the robot -->
  <joint name="$(arg prefix_left)fts_fix" type="fixed" >
    <origin xyz="0 0 0" rpy="0 1.57 0"/>
    <parent link="$(arg prefix_left)ee_link" />
    <child link="fts_robotside" />
  </joint>
	
    <!-- Here we define a flange link between the tip of the iiwa7 and the base of the robotiq. -->
  <!-- Insert a cylinder between default (smaller) flange and robotiq. -->
  <link name="flange">
    <visual>
      <geometry>
        <!-- Length and radius computed by SGD (Semi-stochastic GraduateStudent Descent). -->
        <cylinder length="0.03" radius="0.035"/>
      </geometry>
      <material name="orange">
        <color rgba="1.0 0.27 0.0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.03" radius="0.035"/>
      </geometry>
    </collision>
  </link>


	  <!-- The offset between ee_link and palm was estimated to be 0.0975.
       Sum of z origin displacements of ee_to_flange and robotiq_joint. -->
  <joint name="ee_to_flange" type="fixed">
    <parent link="fts_toolside"/>
    <child link="flange"/>
    <origin xyz ="0.0 0.0 0.015" rpy="0 0 0" />
  </joint>
	
	<!-- Instantiate the robotiq model from the imported macro.  -->
  <xacro:robotiq-3f-gripper_articulated prefix=""/>
	  <joint name="robotiq_joint" type="fixed">
    <parent link="flange" />
    <child link = "palm" />
    <origin xyz="0.0 0 0.06" rpy="${PI/2} 0 0" />  
  	</joint>
		
<!--
  <joint name="$(arg prefix_left)ee_mount" type="fixed">
    <parent link="$(arg prefix_left)tool0"/>
    <child link ="$(arg prefix_left)ee_frame"/>
    <origin xyz="0 0 0" rpy="0 0 ${PI}" />
  </joint>
-->
  <!-- place ur5 right arm  -->
  <xacro:ur5_robot prefix="$(arg prefix_right)" joint_limited="$(arg limited)"/>
  <joint name="stand2_to_right_arm" type="fixed">
    <parent link="stand2"/>
    <child link ="$(arg prefix_right)base_link"/>
    <origin xyz="0 0 -${(robot_horizontal_stand_width/2)}" rpy="${PI/4.0} ${PI} 0"/>
  </joint>

  <!-- place 2 finger gripper on right arm -->
  <xacro:robotiq_c2_model prefix=""/>
  <joint name="$(arg prefix_right)ee_mount" type="fixed">
    <parent link="$(arg prefix_right)ee_link" />
    <child link = "robotiq_85_adapter_link" />
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
  </joint>
	
  
<!--
  <joint name="$(arg prefix_right)ee_mount" type="fixed">
    <parent link="$(arg prefix_right)tool0"/>
    <child link ="$(arg prefix_right)ee_frame"/>
    <origin xyz="0 0 0" rpy="0 0 ${PI}" />
  </joint>
-->
</robot>
