sudo: required
dist: trusty
language: generic

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    - ROS_DISTRO="indigo"  ROS_REPO=ros              NOT_TEST_INSTALL=true
    - ROS_DISTRO="indigo"  ROS_REPO=ros-shadow-fixed NOT_TEST_INSTALL=true
    - ROS_DISTRO="kinetic" ROS_REPO=ros              NOT_TEST_INSTALL=true
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed NOT_TEST_INSTALL=true
    - ROS_DISTRO="kinetic" CLANG_FORMAT_CHECK=file

install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script: 
  - .ci_config/travis.sh
