controller_list:
  - name: "compliance_controller"  # This name is set particular for ur_complicance, if you do not work on this project, please reset it back to empty.
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
