### ros-control settings:
controller_list:
  - name: left/left_vel_based_pos_traj_controller #or pos_based_pos_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint

  - name: right/right_vel_based_pos_traj_controller #or pos_based_pos_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint

##-------------for real gripper-----------------------------
  - name: /joint_position_controller #/simple_gripper/joint_position_controller
    action_ns: gripper_cmd #follow_joint_trajectory #Robotiq2FCommand #gripper_action #gripper_cmd
    type: GripperCommand #FollowJointTrajectory #Robotiq2FActionController #GripperCommand
   default: true
    joints:
      - robotiq_85_left_knuckle_joint
    initial:
     - group: right_gripper
       pose:  open

