fake_interpolating_controller_rate: 10 (Hz)
controller_list:
  - name: fake_ur5_manipulator_controller
    type: interpolate   #interpolate | via points | last point
    joints:
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint
  - name: fake_right_manipulator_controller
    type: interpolate
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: fake_ur5_endeffector_controller
    joints:
      []
  - name: fake_right_endeffector_controller
    joints:
      []
initial:
  - group: arms
    pose:  arms_up


#  - name: fake_arms_controller
#    joints:
#      - right_shoulder_pan_joint
#      - right_shoulder_lift_joint
#      - right_elbow_joint
#      - right_wrist_1_joint
#      - right_wrist_2_joint
#      - right_wrist_3_joint
#      - ur5_shoulder_pan_joint
#      - ur5_shoulder_lift_joint
#      - ur5_elbow_joint
#      - ur5_wrist_1_joint
#      - ur5_wrist_2_joint
#      - ur5_wrist_3_joint
